//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCLauncher.net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCLauncher.net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} files!.
        /// </summary>
        internal static string addedfiles {
            get {
                return ResourceManager.GetString("addedfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added these files.
        /// </summary>
        internal static string addedthesefiles {
            get {
                return ResourceManager.GetString("addedthesefiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding....
        /// </summary>
        internal static string adding {
            get {
                return ResourceManager.GetString("adding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled!.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to minecraft.net.
        /// </summary>
        internal static string cantconnectmcnet {
            get {
                return ResourceManager.GetString("cantconnectmcnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking MCBans....
        /// </summary>
        internal static string checkingmcbans {
            get {
                return ResourceManager.GetString("checkingmcbans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the Jar!.
        /// </summary>
        internal static string couldnotreadjar {
            get {
                return ResourceManager.GetString("couldnotreadjar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save notes. Error:.
        /// </summary>
        internal static string couldnotsavenotes {
            get {
                return ResourceManager.GetString("couldnotsavenotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Finished.
        /// </summary>
        internal static string dlfinished {
            get {
                return ResourceManager.GetString("dlfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have still downloads going. Closing this window will cancel them all!.
        /// </summary>
        internal static string dlmanclose {
            get {
                return ResourceManager.GetString("dlmanclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close the Download Manager?.
        /// </summary>
        internal static string dlmanclosetitle {
            get {
                return ResourceManager.GetString("dlmanclosetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Starting.
        /// </summary>
        internal static string dlstarting {
            get {
                return ResourceManager.GetString("dlstarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Stopped.
        /// </summary>
        internal static string dlstopped {
            get {
                return ResourceManager.GetString("dlstopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} out of {1} ({2}%).
        /// </summary>
        internal static string downloadedoutof {
            get {
                return ResourceManager.GetString("downloadedoutof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop files here.
        /// </summary>
        internal static string dragfileshere {
            get {
                return ResourceManager.GetString("dragfileshere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string errordetail {
            get {
                return ResourceManager.GetString("errordetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving notes.
        /// </summary>
        internal static string errorwhilesavingnotes {
            get {
                return ResourceManager.GetString("errorwhilesavingnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jar not found!.
        /// </summary>
        internal static string jarnotfound {
            get {
                return ResourceManager.GetString("jarnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jar was not found at {0}. Please check if the file exists..
        /// </summary>
        internal static string jarnotfoundat {
            get {
                return ResourceManager.GetString("jarnotfoundat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java not found.
        /// </summary>
        internal static string javanotfound {
            get {
                return ResourceManager.GetString("javanotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java was not found on this computer. You need Java to run Minecraft. If you do not have Java, you can download it from http://java.com/ \nIf you do have Java, please click Yes and select it..
        /// </summary>
        internal static string javanotfounddesc {
            get {
                return ResourceManager.GetString("javanotfounddesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to reopen the launcher to change the language..
        /// </summary>
        internal static string langwillchangeinfo {
            get {
                return ResourceManager.GetString("langwillchangeinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application restart needed.
        /// </summary>
        internal static string langwillchangetitle {
            get {
                return ResourceManager.GetString("langwillchangetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        internal static string loggingin {
            get {
                return ResourceManager.GetString("loggingin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string loginfailed {
            get {
                return ResourceManager.GetString("loginfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated launcher, contact jessenic at digiex.net.
        /// </summary>
        internal static string outdatedlauncher {
            get {
                return ResourceManager.GetString("outdatedlauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing login....
        /// </summary>
        internal static string processinglogin {
            get {
                return ResourceManager.GetString("processinglogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing MCBans....
        /// </summary>
        internal static string processingmcbans {
            get {
                return ResourceManager.GetString("processingmcbans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0}.
        /// </summary>
        internal static string removedfile {
            get {
                return ResourceManager.GetString("removedfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing the Main Frame....
        /// </summary>
        internal static string showingmainframe {
            get {
                return ResourceManager.GetString("showingmainframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Download.
        /// </summary>
        internal static string startdl {
            get {
                return ResourceManager.GetString("startdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have too low ban rep! Check MCBans.com!.
        /// </summary>
        internal static string toolowrep {
            get {
                return ResourceManager.GetString("toolowrep", resourceCulture);
            }
        }
    }
}
