//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCLauncher.net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCLauncher.net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string advancedsettings {
            get {
                return ResourceManager.GetString("advancedsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled!.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to minecraft.net.
        /// </summary>
        internal static string cantconnectmcnet {
            get {
                return ResourceManager.GetString("cantconnectmcnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking MCBans....
        /// </summary>
        internal static string checkingmcbans {
            get {
                return ResourceManager.GetString("checkingmcbans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jar Manager.
        /// </summary>
        internal static string jarmanager {
            get {
                return ResourceManager.GetString("jarmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java not found.
        /// </summary>
        internal static string javanotfound {
            get {
                return ResourceManager.GetString("javanotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java was not found on this computer. You need Java to run Minecraft. If you do not have Java, you can download it from http://java.com/ \nIf you do have Java, please click Yes and select it..
        /// </summary>
        internal static string javanotfounddesc {
            get {
                return ResourceManager.GetString("javanotfounddesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java installation path.
        /// </summary>
        internal static string javapath {
            get {
                return ResourceManager.GetString("javapath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        internal static string launch {
            get {
                return ResourceManager.GetString("launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        internal static string loggingin {
            get {
                return ResourceManager.GetString("loggingin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string loginfailed {
            get {
                return ResourceManager.GetString("loginfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum memory.
        /// </summary>
        internal static string maxmem {
            get {
                return ResourceManager.GetString("maxmem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated launcher, contact jessenic at digiex.net.
        /// </summary>
        internal static string outdatedlauncher {
            get {
                return ResourceManager.GetString("outdatedlauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing login....
        /// </summary>
        internal static string processinglogin {
            get {
                return ResourceManager.GetString("processinglogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing MCBans....
        /// </summary>
        internal static string processingmcbans {
            get {
                return ResourceManager.GetString("processingmcbans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string rememberme {
            get {
                return ResourceManager.GetString("rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots.
        /// </summary>
        internal static string screenshots {
            get {
                return ResourceManager.GetString("screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select JAR.
        /// </summary>
        internal static string selectjar {
            get {
                return ResourceManager.GetString("selectjar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing the Main Frame....
        /// </summary>
        internal static string showingmainframe {
            get {
                return ResourceManager.GetString("showingmainframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have too low ban rep! Check MCBans.com!.
        /// </summary>
        internal static string toolowrep {
            get {
                return ResourceManager.GetString("toolowrep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
